### PR TITLE
allow using a file provider instead of a template

### PR DESCRIPTION
**Pull request by lamont-granquist**
- introduces a new 'lines' property that feeds into a file resource
  instead of using a template

### CODE REVIEW

**Comment by lamont-granquist** [comment]
i hate the name of this property it should probably be named 'rules' or something.

**Comment by lamont-granquist** [comment]
probably closes #34 
probably closes #25

**Comment by lamont-granquist** [comment]
the no-template-centos-72 kitchen test is busted but the default-centos-72 kitchen test seems to also be busted

**Comment by tas50** [comment]
Add documentation for how to use this.

**Comment by lamont-granquist** [comment]
docs added.

the docs should close #25

**Pull request merged**
