### PR TITLE
Feature/ipv6

### PR DESCRIPTION
**Pull request by elthariel**
### Description

This PR adds IPv6 support to this cookbook.  It basically just duplicates IPv4 support

### Issues Resolved

refs #32 

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

I haven't signed the DCO, but my commits are `Signed-Off` as I think this is the new policy ?

### CODE REVIEW

**Comment by elthariel** [comment]
PS: The lint errors are not part of this PR

**Comment by rmoriz** [comment]
can you fix conflicts?

**Comment by elthariel** [comment]
@rmoriz Should be good. Feel free to squash before merging

**Comment by tas50** [comment]
Thanks @elthariel

**Pull request merged**
